### ISSUE TITLE
Getting IO error with this installed

### ISSUE THREAD

**Issue by HalJordan** [poralix/rspamd#3]
Both rspamd and rspamc work fine without the plugin(I had to nuke /etc/rspamd and /var/lib/rspamd after stopping all services/processes and uninstalling rspamd, then manually installed rspamd from yum):
```
# rspamd --version
Rspamd daemon version 3.2
# rspamc stat
Results for command: stat (0.114 seconds)
Messages scanned: 0
Messages learned: 0
Connections count: 0
Control connections count: 0
Pools allocated: 31
Pools freed: 6
Bytes allocated: 26.81MiB
Memory chunks allocated: 135
Shared chunks allocated: 15
Chunks freed: 0
Oversized chunks: 2
Fuzzy hashes in storage "rspamd.com": 1775194213
Fuzzy hashes stored: 1775194213
Total learns: 0
```

After this plugin is installed, I only get an I/O error:
```
# rspamc stat
Results for command: stat (0.000 seconds)
IO write error: Connection refused
```

**Comment by gralex54** [comment]
Hello,

The plugin from Poralix does not change anything in rSpamd setup. If you run a directadmin server, then it explains the behaviour. DirectAdmin changes rSpam to use sockets instead of ports. And the suggested command will work the following way:

```
rspamc --connect /var/lib/rspamd/rspamd.sock stat
```

You might check rSpamd documentation on how to make the socket to be used by default.
