### ISSUE TITLE
Bug in menu link

### ISSUE THREAD

**Issue by NZECKCO** [poralix/rspamd#5]
It appears that this link

`<a href="/CMD_PLUGINS_ADMIN/rspamd/index.raw" target="_top">Rspamd Web Interface</a>`

Causes an error connecting to local storage, took a while to work out the issue was just this link and not the install of Rspamd or Redis.

So far as a workaround I added

`<a href="/CMD_RSPAMD_SOCK/" target="_blank">Rspamd Web Interface</a>` <-- works fine in a new tab

Using Ububtu 22.0.4 latest stable DA

**Comment by gralex54** [comment]
Hello,

Since that you don't use the plugin. You open a native DirectAdmin module for rSpamd.

We were first to add the Web interface into DirectAdmin, and then only DirectAdmin developers did the same. And as soon as they added a native support, they changed a port to a socket. 

To solve the issue you can re-install the plugin.
